const STORE_KEY = "morkborg-sd-engine-v1";

const tables = {
  names: ["Aerg-Tval", "Agn", "Arvant", "Belsum", "Belum", "Brint", "Borda", "Daeru", "Eldar", "Felban", "Gotven", "Graft", "Grin", "Grittr", "Haeru", "Hargha", "Harmug", "Jotna", "Karg", "Karva", "Katla", "Keftar", "Klort", "Kratar", "Kutz", "Kvetin", "Lygan", "Margar", "Merkari", "Nagl", "Niduk", "Nifehl", "Prugl", "Qillnach", "Risten", "Svind", "Theras", "Therg", "Torvul", "Torn", "Urm", "Urvarg", "Vagal", "Vatan", "Von", "Vrakh", "Vresi", "Wemut"],
  weapons: [["Femur", "d4"], ["Staff", "d4"], ["Shortsword", "d4"], ["Knife", "d4"], ["Warhammer", "d6"], ["Sword", "d6"], ["Bow", "d6"], ["Flail", "d8"], ["Crossbow", "d8"], ["Zweihander", "d10"]],
  containers: ["Nothing", "Backpack for 7 items", "Sack for 10 items", "Small wagon", "Donkey"],
  gearA: ["Rope, 30 feet", "Torches", "Lantern and oil", "Magnesium strip", "Random unclean scroll", "Sharp needle", "Medicine box", "Bear trap", "Lockpicks", "Metal file", "Exquisite perfume", "Silver crucifix"],
  gearB: ["Blanket", "Caltrops", "Chalk", "Chewing tobacco", "Firesteel", "Hammer", "Iron nails", "Grappling hook", "Shield", "Crowbar", "Noose", "Tent"],
  traits: ["Endlessly aggravated", "Inferiority complex", "Problems with authority", "Loud mouth", "Cruel", "Egocentric", "Nihilistic", "Prone to substance abuse", "Conflicted", "Shrewd", "Vindictive", "Cowardly", "Lazy", "Suspicious", "Ruthless", "Worried", "Bitter", "Deceitful", "Wasteful", "Arrogant"],
  bodies: ["Manic gaze", "Blasphemous tattoos", "Rotting masked face", "Lost toes, limps", "Starved and pale", "Rusting hook hand", "Decaying teeth", "Unnervingly clean", "Hands caked with sores", "Spreading cataracts", "Tangled hair", "Crushed ears", "Juddering speech", "Corpulent hunger", "Lobster-like grip", "Alcoholic nose", "Resting maniac face", "Chronic stink", "Fresh eye patch", "Black cracked nails"],
  habits: ["Collects sharp stones", "Tests blades on flesh", "Cannot stop drinking", "Gambling addict", "Cannot tolerate criticism", "Never finishes stories", "Best friend is a skull", "Nose-picking bleeds", "Explains own jokes", "Lectures about nihilism", "Eats bugs", "Gets fancy under stress", "Permanent throat phlegm", "Pyromaniac", "Loses important things", "Talks behind backs", "Stutters when lying", "Giggles at awful times", "Whistles while hiding", "Makes tooth jewelry"],
  roomAdjectives: ["Dark", "Neglected", "Acrid", "Rotten", "Oppressive", "Unholy", "Deathly", "Deceptive", "Bleak", "Infested", "Deserted", "Ancient", "Extravagant", "Crowded", "Carven", "Rustic", "Misty", "Defaced", "Flooded", "Unnatural"],
  roomTypes: ["Crypt or abattoir", "Stream, pool, or chasm", "Prison, cell, stable, or zoo", "Store, kitchen, or nest", "Cavern or passage", "Stairwell, ladder, or pit", "Chamber or clearing", "Lair or dwelling", "Shrine or temple", "Workshop, library, or forge", "Doorway or entrance", "Catacomb or hall"],
  roomContents: ["Bizarre creature", "Remains of something", "Unexpected event", "Gathering, ritual, or group", "Blocked path", "Common encounter", "Common encounter", "Rare encounter", "Human NPC", "Hazardous environment", "Object of interest", "Looks empty"],
  streetAdj: ["Shadowed", "Crumbling", "Sinking", "Cursed", "Isolated", "Fortified", "Besieged", "Polluted", "Condemned", "Ruinous", "Tottering", "Seedy", "Squatting", "Brooding", "Sodden", "Fogbound", "Dusty", "Forgotten", "Decaying", "Pestilential"],
  stockCreatures: ["Regional creature", "Pale One", "Dusk Gnoum", "Scum", "Blood-drenched skeleton", "Zombie", "Mongrel", "Goblin", "Guards with sharpened teeth", "Earthbound", "Prowler", "Wickhead knife-wielder", "Wraith", "Undead doll", "Nesting death", "Lich", "Berserker", "Wyvern", "Grotesque", "Troll"],
  commonEncounters: ["Mongrel", "Pale One", "Earthbound", "Scum", "Hungry corpse", "Useful item", "Lost pilgrim", "Screaming captive"],
  rareEncounters: ["Wickhead", "Nesting Death", "Undead Doll", "Berserker", "Wyvern", "Tenebrous relic", "Lich", "Troll"],
  dispositions: ["Cursed", "Bloodthirsty", "Drunken", "Melancholic", "Malign", "Greedy", "Reclusive", "Eccentric", "Awkward", "Dishonest", "Generous", "Suspicious", "Ragged", "Pestilent", "Heretical", "Wretched", "Hermetic", "Wounded", "Gaunt", "Burly", "Insincere", "Narcissistic", "Spiteful", "Rude", "Nihilistic", "Friendly", "Ancient", "Extravagant", "Possessed", "Hopeless", "Scared", "Exiled", "Fanatical", "Penitent", "Creepy", "Profane"],
  professions: ["Alchemist", "Necromancer", "Tailor", "Blacksmith", "Mercenary", "Merchant", "Rogue", "Noble", "Guard", "Butcher", "Cook", "Serf", "Scribe", "Priest", "Tanner", "Trapper", "Assassin", "Prisoner", "Musician", "Servant", "Jailer", "Inquisitor", "Innkeeper", "Barber-surgeon", "Grave-robber", "Gravedigger", "Seer", "Artisan", "Beggar", "Performer", "Nightsoil collector", "Executioner", "Smuggler", "Horseman", "Toad catcher", "Prophet"],
  traps: ["Poisonous arrows from wall-holes", "Bells and marbles on the floor", "Falling scorpion basket", "Fish hooks at eye level", "Explosive rune chest", "Poison gas lock", "Jewel removal roof collapse", "Oil-slick slanted floor and pit", "Snake cages above", "Cold ghosts in evil urns", "Poisoned coins", "Collapsing ceiling tiles"],
  weakHits: ["Small damage", "New danger", "Lose an item or silver", "Unintended negative effect", "Surprising negative development", "Someone is put in harm's way"],
  dangers: ["Trap", "Locked door or obstruction", "Environmental danger", "Common encounter", "Resource used", "NPC with poor reaction"],
  eventFocus: ["Faction action", "New NPC", "NPC positive", "PC positive", "Plot progress", "NPC action", "PC negative", "Plot obstacle", "NPC negative", "Environment", "Plot twist"],
  weather: ["Lifeless grey", "Hammering rain", "Piercing wind", "Deafening storm", "Black as night", "Dead quiet", "Cloudburst", "Soup-thick mist", "Crackling frost", "Irritating drizzle", "Roaring thunder", "Gravelike cold"],
  settlementNames: ["Ghast Pit", "Blood Brae", "Scar Borg", "Dog's Cot", "Corpse Field", "Old Kirke", "Nether Stone", "Unter Heim", "Devil Moor", "Grave Beck", "Dead Mere", "Sar Gut", "Beggars Lees", "Wraith Dike", "Scum Gash", "Rat Tor", "Flaying Kulle", "Wolven Mark", "Night Falls", "Mork Dale", "Witch Heath", "Goblin Caul", "Grey Hall", "Knife Hill", "Wretched Wood", "Gloom Spire", "Bone Gate", "Spittle Scythe", "Grime Skull", "Idol Ash", "Gull's Crypt", "Wast Peak", "Gallow's Croft", "Candle Wold", "Salt Bridge", "Withered Fort"]
};

const references = [
  ["Mork Borg Bare Bones Edition", "C:\\Users\\rober\\OneDrive\\MORK BORG\\MORK BORG BARE BONES EDITION.pdf"],
  ["Solitary Defilement Rulebook", "C:\\Users\\rober\\OneDrive\\MORK BORG\\1_-_Solitary_Defilement_Rulebook.pdf"],
  ["Alone in the Crowd", "C:\\Users\\rober\\OneDrive\\MORK BORG\\3_-_Alone_in_the_Crowd.pdf"],
  ["Worksheets", "C:\\Users\\rober\\OneDrive\\MORK BORG\\4a_-_Worksheets.pdf"],
  ["Solitary Depths", "C:\\Users\\rober\\OneDrive\\MORK BORG\\Solitary Depths.pdf"],
  ["Bone Slave", "C:\\Users\\rober\\OneDrive\\MORK BORG\\Classes\\Bone Slave A4 H.pdf"],
  ["Damned Blade-Thrall", "C:\\Users\\rober\\OneDrive\\MORK BORG\\Classes\\damned blade-thrall.pdf"],
  ["Fugitive Knight", "C:\\Users\\rober\\OneDrive\\MORK BORG\\Classes\\Fugitive Knight (A4) Horizontal PDF.pdf"]
];

const defaultState = { campaignName: "A Miserable Little Campaign", activeCharacterId: null, characters: [], dungeon: null, rooms: [], journal: [], threads: [], miseryIndex: 0, lastOracle: "None" };
let state = loadState();
let editingEntryId = null;

function roll(sides, count = 1) { let total = 0; const rolls = []; for (let i = 0; i < count; i++) { const value = Math.floor(Math.random() * sides) + 1; rolls.push(value); total += value; } return { total, rolls }; }
function pick(array) { return array[Math.floor(Math.random() * array.length)]; }
function abilityFromRoll(total) { if (total <= 4) return -3; if (total <= 6) return -2; if (total <= 8) return -1; if (total <= 12) return 0; if (total <= 14) return 1; if (total <= 16) return 2; return 3; }
function signed(value) { return value > 0 ? `+${value}` : `${value}`; }
function uid(prefix) { return `${prefix}-${Date.now()}-${Math.random().toString(16).slice(2)}`; }
function saveState() { localStorage.setItem(STORE_KEY, JSON.stringify(state)); }
function loadState() { try { return { ...defaultState, ...JSON.parse(localStorage.getItem(STORE_KEY) || "{}") }; } catch { return { ...defaultState }; } }

function generateCharacter(playbook = "Classless Scvm", mode = "standard") {
  const abilities = {};
  const boosted = mode === "forgiving" && playbook === "Classless Scvm" ? ["agility", "presence"].sort(() => Math.random() - .5).slice(0, 2) : [];
  for (const stat of ["agility", "presence", "strength", "toughness"]) {
    const dice = roll(6, boosted.includes(stat) ? 4 : 3).rolls;
    const kept = boosted.includes(stat) ? dice.sort((a, b) => b - a).slice(0, 3) : dice;
    abilities[stat] = abilityFromRoll(kept.reduce((a, b) => a + b, 0));
  }
  if (playbook === "Damned Blade-Thrall") { abilities.toughness = abilityFromRoll(roll(6, 3).total + 2); abilities.presence = abilityFromRoll(Math.max(3, roll(6, 3).total - 2)); }
  const hpDie = playbook === "Damned Blade-Thrall" ? 10 : 8;
  const hp = Math.max(1, abilities.toughness + roll(hpDie).total);
  const weapon = playbook === "Damned Blade-Thrall" ? ["Cursed zweihander", "d10"] : pick(tables.weapons);
  const silver = roll(6, 2).total * 10;
  const omens = playbook === "Damned Blade-Thrall" ? roll(4).total : roll(2).total;
  const notes = [];
  if (playbook === "Bone Slave" || playbook === "Fugitive Knight") notes.push("Open the class PDF in References and add playbook-specific traits here.");
  if (playbook === "Damned Blade-Thrall") notes.push(`Burden: ${pick(["Pried from a cemetery monument", "Bought from a faceless merchant", "Taken after betrayal", "Freed from Kergus ice", "Inherited from a Galgenbeck priest", "Offered by a mud-pit demon"])}`);
  return { id: uid("pc"), name: pick(tables.names), playbook, hp, maxHp: hp, omens, maxOmens: omens, silver, abilities, weapon: `${weapon[0]} (${weapon[1]})`, armor: pick(["No armor", "Light armor", "Medium armor", "Heavy armor"]), gear: [pick(tables.containers), pick(tables.gearA), pick(tables.gearB), "Waterskin", `${roll(4).total} days of food`], traits: [pick(tables.traits), pick(tables.bodies), pick(tables.habits)], notes };
}

function rollMove(dr, modifier) { const a = roll(20).total + modifier; const b = roll(20).total + modifier; const hits = Number(a >= dr) + Number(b >= dr); return { a, b, dr, modifier, label: hits === 2 ? "Strong Hit" : hits === 1 ? "Weak Hit" : "Fail", className: hits === 2 ? "success" : hits === 1 ? "weak" : "danger" }; }
function generateDungeon() { return { name: `${pick(tables.roomAdjectives)} ${pick(["Sepulcher", "Vault", "Cistern", "Manse", "Wound", "Chapel", "Pit", "Ossuary"])}`, status: pick(["Abandoned", "Occupied", "Flooded", "Recently opened", "Half-collapsed", "Actively changing"]), dwellers: pick(tables.stockCreatures), entrance: `${pick(tables.roomAdjectives)} ${pick(tables.roomTypes)}`, danger: pick(["Something below is waking", "The air eats torchlight", "A faction is already inside", "The doors rearrange", "The dead know your name", "A bell rings when blood spills"]), hook: pick(["Recover a debt", "Find a missing child", "Steal a relic", "Hide from hunters", "Break a curse", "Loot before the inquisition arrives"]), guardedBy: pick(tables.stockCreatures), feature: `${pick(tables.weather)}; ${pick(["black fungus", "bone dust", "warm walls", "wet hymns", "silver insects", "breathing stone"])}`, specialRooms: [1, 2, 3, 4].map(i => `Special ${i}: ${pick(tables.roomAdjectives)} ${pick(tables.roomTypes)} with ${pick(tables.roomContents).toLowerCase()}`), dr: Number(document.getElementById("dungeonDr").value), tr: Number(document.getElementById("threatRating").value), specialsFound: 0 }; }
function roomExits(specials) { const options = specials >= 4 ? [1, 1, 1] : specials >= 2 ? [1, 1, 2] : [1, 2, 2, 3]; return pick(options); }
function generateRoom() { if (!state.dungeon) state.dungeon = generateDungeon(); const move = rollMove(state.dungeon.dr, state.dungeon.specialsFound); let title; let text; if (move.label === "Strong Hit" && state.dungeon.specialsFound < 4) { state.dungeon.specialsFound += 1; title = `Special Room ${state.dungeon.specialsFound}`; text = state.dungeon.specialRooms[state.dungeon.specialsFound - 1]; } else if (move.label === "Fail") { title = "Blocked by danger"; text = `${pick(tables.dangers)}: ${pick([...tables.traps, ...tables.commonEncounters, "A locked obstruction", "A hostile environment"])}`; } else { title = `${pick(tables.roomAdjectives)} ${pick(tables.roomTypes)}`; text = `${pick(tables.roomContents)}. Exits: ${roomExits(state.dungeon.specialsFound)}. ${pick(["A smell lingers.", "Sound carries strangely.", "The floor remembers violence.", "Something has been dragged through here."])}`; } const entry = { id: uid("room"), title, text, move, at: new Date().toLocaleString() }; state.rooms.unshift(entry); saveState(); return entry; }
function yesNoOracle() { return ["Yes", "Yes, but", "No, but", "No"][roll(4).total - 1]; }
function depthOracle(chance = "even") { const rolls = chance === "likely" ? roll(20, 2).rolls : chance === "unlikely" ? roll(20, 2).rolls : [roll(20).total]; const value = chance === "likely" ? Math.max(...rolls) : chance === "unlikely" ? Math.min(...rolls) : rolls[0]; if (value === 10) return `Random Event: ${pick(tables.eventFocus)}`; if (value > 10) return value >= 20 ? "Yes, and" : "Yes"; return value <= 1 ? "No, and" : "No"; }
function rollReaction(mod = 0) { const value = roll(6, 2).total + mod; if (value <= 3) return `${value}: Kill`; if (value <= 6) return `${value}: Angered`; if (value <= 8) return `${value}: Indifferent`; if (value <= 10) return `${value}: Almost friendly`; return `${value}: Helpful`; }

function render() { document.getElementById("campaignName").value = state.campaignName; document.getElementById("currentDate").textContent = new Date().toLocaleDateString([], { weekday: "long", month: "long", day: "numeric" }); document.getElementById("miseryDie").textContent = ["d20", "d12", "d10", "d8", "d6", "d4", "d2"][state.miseryIndex] || "7:7"; document.getElementById("threadCount").textContent = state.threads.filter(t => !t.done).length; document.getElementById("lastOracle").textContent = state.lastOracle; renderActiveCharacter(); renderCharacters(); renderDungeon(); renderRooms(); renderThreads(); renderJournal(); renderReferences(); }
function renderActiveCharacter() { const pc = state.characters.find(c => c.id === state.activeCharacterId) || state.characters[0]; const el = document.getElementById("activeCharacter"); if (!pc) { el.textContent = "No character has crawled out of the mud yet."; return; } state.activeCharacterId = pc.id; el.innerHTML = characterHtml(pc, false); }
function characterHtml(pc, withActions = true) { return `<div class="character-card"><header><div><h4>${escapeHtml(pc.name)}</h4><div class="meta"><span class="pill">${escapeHtml(pc.playbook)}</span><span class="pill">HP ${pc.hp}/${pc.maxHp}</span><span class="pill">Omens ${pc.omens}</span><span class="pill">${pc.silver}s</span></div></div>${withActions ? `<button class="small set-active" data-id="${pc.id}">Set Active</button>` : ""}</header><div class="stats">${Object.entries(pc.abilities).map(([k, v]) => `<div class="stat"><span>${k.slice(0, 3).toUpperCase()}</span><strong>${signed(v)}</strong></div>`).join("")}</div><div class="pill-row"><span class="pill">${escapeHtml(pc.weapon)}</span><span class="pill">${escapeHtml(pc.armor)}</span></div><p>${pc.gear.map(escapeHtml).join(", ")}</p><p>${pc.traits.map(escapeHtml).join(" / ")}</p>${pc.notes.length ? `<p class="weak">${pc.notes.map(escapeHtml).join(" ")}</p>` : ""}</div>`; }
function renderCharacters() { document.getElementById("charactersList").innerHTML = state.characters.map(pc => characterHtml(pc)).join("") || `<div class="empty-state">Roll a character to begin.</div>`; }
function renderDungeon() { const el = document.getElementById("dungeonSheet"); if (!state.dungeon) { el.innerHTML = `<div class="empty-state">No dungeon generated.</div>`; return; } const d = state.dungeon; const rows = [["Name", d.name], ["Status", d.status], ["Dwells There", d.dwellers], ["Entrance", d.entrance], ["Imminent Danger", d.danger], ["What Brings You Here", d.hook], ["Guarded By", d.guardedBy], ["Feature", d.feature], ["Progress", `${d.specialsFound}/4 special rooms`]]; el.innerHTML = rows.map(([a, b]) => `<div class="sheet-row"><span>${a}</span><span>${escapeHtml(b)}</span></div>`).join(""); }
function renderRooms() { document.getElementById("roomLog").innerHTML = state.rooms.map(room => `<div class="list-item"><header><strong>${escapeHtml(room.title)}</strong><span class="pill">${room.move.label}</span></header><p>${escapeHtml(room.text)}</p><small>${room.at}</small></div>`).join(""); }
function renderThreads() { const el = document.getElementById("threadsList"); el.innerHTML = state.threads.map(t => `<div class="list-item"><header><strong>${escapeHtml(t.text)}</strong><button class="small toggle-thread" data-id="${t.id}">${t.done ? "Reopen" : "Resolve"}</button></header><div class="meta"><span class="pill">${t.done ? "Resolved" : "Open"}</span></div></div>`).join("") || `<div class="empty-state">No unresolved business. Suspicious.</div>`; }
function renderJournal() { const el = document.getElementById("entriesList"); el.innerHTML = state.journal.map(entry => `<div class="list-item"><header><strong>${escapeHtml(entry.title)}</strong><button class="small edit-entry" data-id="${entry.id}">Edit</button></header><p>${escapeHtml(entry.body).slice(0, 220)}${entry.body.length > 220 ? "..." : ""}</p><div class="meta"><span class="pill">${entry.date}</span>${entry.tags.map(t => `<span class="pill">${escapeHtml(t)}</span>`).join("")}</div></div>`).join("") || `<div class="empty-state">The journal is clean. This will not last.</div>`; }
function renderReferences() { document.getElementById("movesReference").innerHTML = [["General Move", "Roll 2d20 plus stat against DR 6, 12, or 18. Two hits: strong. One hit: weak. No hits: fail."], ["Dungeon Crawl", "Roll dungeon DR plus special rooms found. Strong reaches a special room, weak creates a room, fail reveals danger."], ["City Crawl", "Roll city DR. Strong reaches an objective, weak creates a street, fail blocks movement with an encounter."], ["Threat Rating", "Use TR 9, 12, or 15 for trap, obstruction, enemy detection, and hazard moves."], ["Weak Hit", `When stuck: ${tables.weakHits.join("; ")}.`]].map(([a, b]) => `<div class="list-item"><strong>${a}</strong><p>${b}</p></div>`).join(""); document.getElementById("sourcesReference").innerHTML = references.map(([name, path]) => { const url = `file:///${path.replace(/\\/g, "/").replace(/ /g, "%20")}`; return `<div class="list-item"><strong>${name}</strong><p><a href="${escapeHtml(url)}">${escapeHtml(path)}</a></p></div>`; }).join(""); }
function escapeHtml(value) { return String(value).replace(/[&<>"']/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c])); }

document.addEventListener("click", event => {
  const tab = event.target.closest(".tab");
  if (tab) { document.querySelectorAll(".tab, .view").forEach(el => el.classList.remove("active")); tab.classList.add("active"); document.getElementById(tab.dataset.view).classList.add("active"); document.getElementById("heroTitle").textContent = tab.textContent === "Desk" ? "The desk is open." : tab.textContent; }
  if (event.target.id === "newCharacter" || event.target.id === "quickCharacter") { const pc = generateCharacter(document.getElementById("classSelect").value, document.getElementById("creationMode").value); state.characters.unshift(pc); state.activeCharacterId = pc.id; saveState(); render(); }
  if (event.target.classList.contains("set-active")) { state.activeCharacterId = event.target.dataset.id; saveState(); render(); }
  if (event.target.id === "rollMove") { const pc = state.characters.find(c => c.id === state.activeCharacterId); const stat = document.getElementById("moveStat").value; const statMod = pc && stat ? (stat === "omens" ? pc.omens : pc.abilities[stat]) : 0; const manual = Number(document.getElementById("moveMod").value); const result = rollMove(Number(document.getElementById("moveDr").value), manual + statMod); document.getElementById("moveResult").innerHTML = `<strong class="${result.className}">${result.label}</strong><span>${result.a} and ${result.b} vs DR ${result.dr} (${signed(result.modifier)})</span>`; }
  if (event.target.id === "rollMisery") { const die = [20, 12, 10, 8, 6, 4, 2][state.miseryIndex]; if (!die) state.lastOracle = "The seventh Misery ends the world."; else { const value = roll(die).total; state.lastOracle = value === 1 ? `Misery awakens. Roll d66 in the book.` : `No Misery: ${value} on d${die}`; if (value === 1) state.miseryIndex += 1; } saveState(); render(); }
  if (event.target.id === "yesNoDesk") { state.lastOracle = `${yesNoOracle()} / ${depthOracle()}`; saveState(); render(); }
  if (event.target.id === "addThread") { const text = prompt("Thread"); if (text) { state.threads.unshift({ id: uid("thread"), text, done: false }); saveState(); render(); } }
  if (event.target.classList.contains("toggle-thread")) { const thread = state.threads.find(t => t.id === event.target.dataset.id); thread.done = !thread.done; saveState(); render(); }
  if (event.target.id === "clearResolved") { state.threads = state.threads.filter(t => !t.done); saveState(); render(); }
  if (event.target.id === "newDungeon") { state.dungeon = generateDungeon(); state.rooms = []; saveState(); render(); }
  if (event.target.id === "exploreRoom") { const room = generateRoom(); document.getElementById("roomResult").innerHTML = `<strong class="${room.move.className}">${escapeHtml(room.title)}</strong><span>${escapeHtml(room.text)}</span>`; render(); }
  if (event.target.id === "newStreet") { const street = `${pick(tables.streetAdj)} street near ${pick(["a market", "a holy place", "a civic building", "a collapsed road", "a bathhouse", "a locked gate"])}. ${pick(tables.roomContents)}.`; document.getElementById("cityResult").innerHTML = `<strong>${escapeHtml(pick(tables.settlementNames))}</strong><span>${escapeHtml(street)}</span>`; }
  if (event.target.id === "rollEncounter") { const result = encounter(document.getElementById("encounterDanger").value, Number(document.getElementById("reactionMod").value)); document.getElementById("encounterResult").innerHTML = `<strong>${escapeHtml(result.title)}</strong><span>${escapeHtml(result.text)}</span>`; }
  if (event.target.id === "addCombatant") { const name = prompt("Enemy name") || pick(tables.stockCreatures); const hp = roll(8).total; const item = document.createElement("div"); item.className = "list-item"; item.innerHTML = `<header><strong>${escapeHtml(name)}</strong><span class="pill">HP ${hp}</span></header><div class="meta"><span class="pill">Morale ${roll(4).total + 6}</span><span class="pill">Damage d${pick([2,4,6,8])}</span></div>`; document.getElementById("combatants").prepend(item); }
  if (event.target.id === "saveEntry") saveEntry();
  if (event.target.id === "newEntry") clearEntryForm();
  if (event.target.classList.contains("edit-entry")) loadEntry(event.target.dataset.id);
  if (event.target.id === "exportBtn") exportState();
});

document.getElementById("campaignName").addEventListener("input", event => { state.campaignName = event.target.value; saveState(); });
document.getElementById("importFile").addEventListener("change", async event => { const file = event.target.files[0]; if (!file) return; state = { ...defaultState, ...JSON.parse(await file.text()) }; saveState(); render(); });
function encounter(type, mod) { if (type === "npc") return { title: `${pick(tables.dispositions)} ${pick(tables.professions)}`, text: `Reaction: ${rollReaction(mod)}.` }; if (type === "trap") return { title: pick(tables.traps), text: `Find or avoid with a TR move. Weak hit: ${pick(tables.weakHits)}.` }; if (type === "rare") return { title: pick(tables.rareEncounters), text: `Reaction: ${rollReaction(mod)}. First sign: ${pick(tables.weather)}.` }; if (type === "stock") return { title: pick(tables.stockCreatures), text: `Reaction: ${rollReaction(mod)}. If unseen, test TR Agility to learn who notices first.` }; return { title: pick(tables.commonEncounters), text: `Reaction: ${rollReaction(mod)}. Weak-hit consequence: ${pick(tables.weakHits)}.` }; }
function saveEntry() { const title = document.getElementById("entryTitle").value.trim() || "Untitled misery"; const tags = document.getElementById("entryTags").value.split(",").map(t => t.trim()).filter(Boolean); const body = document.getElementById("entryBody").value.trim(); if (!body) return; const existing = state.journal.find(e => e.id === editingEntryId); if (existing) Object.assign(existing, { title, tags, body, date: new Date().toLocaleString() }); else state.journal.unshift({ id: uid("entry"), title, tags, body, date: new Date().toLocaleString() }); editingEntryId = null; clearEntryForm(); saveState(); render(); }
function loadEntry(id) { const entry = state.journal.find(e => e.id === id); if (!entry) return; editingEntryId = id; document.getElementById("entryTitle").value = entry.title; document.getElementById("entryTags").value = entry.tags.join(", "); document.getElementById("entryBody").value = entry.body; }
function clearEntryForm() { editingEntryId = null; document.getElementById("entryTitle").value = ""; document.getElementById("entryTags").value = ""; document.getElementById("entryBody").value = ""; }
function exportState() { const blob = new Blob([JSON.stringify(state, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = `${state.campaignName.replace(/[^a-z0-9]+/gi, "-").toLowerCase()}-solo-engine.json`; a.click(); URL.revokeObjectURL(url); }

render();
